- name: Pull images
  containers.podman.podman_image:
    name: "{{ item.source }}"
    state: present
  loop: "{{ images }}"

- name: Tag image with new tag
  containers.podman.podman_tag:
    image: "{{ item.source }}"
    target_names:
      - "{{ acr_server }}/{{ item.name }}:{{ image_tag }}"
  loop: "{{ images }}"

- name: Login to Azure Container Registry
  containers.podman.podman_login:
    registry:  "{{ acr_server }}"
    username: "{{ acr_name }}"
    password: "{{ acr_password }}"

- name: Push image to ACR
  containers.podman.podman_image:
    name: "{{ acr_server }}/{{ item.name }}:{{ image_tag }}"
    push: true
  loop: "{{ images }}"