- name: Update repositories
  apt:
    update_cache: yes

- name: Install Podman packages
  apt:
    name: "{{ podman_packages }}"
    state: present
    update_cache: yes

- name: Ensure Podman service is enabled (socket)
  systemd:
    name: podman.socket
    state: started
    enabled: yes

- name: Login to Azure Container Registry
  containers.podman.podman_login:
    registry:  "{{ acr_login_server }}"
    username: "{{ acr_name }}"
    password: "{{ acr_password }}"

- name: Pull container image from ACR
  containers.podman.podman_image:
    name: "{{ acr_login_server }}/{{ image_name }}:{{ image_tag }}"
  
- name: Create directory for volume
  file:
    path: /opt/{{ image_name }}
    state: directory
    mode: '0755'

- name: Run container
  containers.podman.podman_container:
    name: "{{ image_name }}"
    image: "{{ image_name }}:{{ image_tag }}"
    state: started
    ports:
      - "{{ container_port }}:80"
    volumes:
      - "/opt/{{ image_name }}:/usr/share/nginx/html"
    restart_policy: always