container_name: wordpress
image_name: wordpress
replicas: 1

# Volume configuration
volume_name: "{{ container_name }}-storage"
volume_mount_path: /var/www/html

# PCV configuration
pvc_name: "{{ container_name }}-pvc"
pvc_storage: 5Gi
pvc_storage_class: managed-csi

# Secret variables
secret_name: "{{ container_name }}-secret"

# Configuration variables
config_name: "{{ container_name }}-config"
wordpress_db_host: mysql
wordpress_db_user: wordpress
container_port: 80
