- name: Push image to ACR
  hosts: acr
  roles:
    - acr

- name: Configure Nginx on VM
  hosts: vm
  become: yes

  roles:
    - vm
  
- name: Deploy WordPress on AKS
  hosts: aks
  roles:
    - acr_secret
    - aks_mysql
    - aks_wordpress