- name: Push image to ACR
  hosts: acr
  roles:
    - acr

- name: Configure Podman host
  hosts: vm
  become: yes

  roles:
    - vm
  
- name: Deploy AKS
  hosts: aks
  roles:
    - acr_secret
    - aks_mysql